### ISSUE TITLE
Status of Cradle - effectively abandoned?

### ISSUE THREAD

**Issue by mike-lang** [flatiron/cradle#297]
Are there any plans to continue development on cradle?  How many developers with commit privileges are left?  Only 9 commits landed in master in 2015 and as of 12/23/15 there are 27 open pull requests and 48 open issues.  As best I can tell, the `flatiron` github organization's sponsor nodejitsu was acquired by GoDaddy in early 2015 and it seems any sponsorship of this project has effectively ended.  

I'm not trying to complain so much as trying to sort out realistic expectations for cradle in the face of what appears to be outdated information regarding sponsors, etc. 

Thanks for your OSS contributions!

**Comment by nullivex** [comment]
+1

I use `cradle` and was wondering about this myself. I am still using cradle but considering nano. I just like the cradle API a bit better.

I think the caching needs work because we forced to turn it off to prevent conflicts. I would like for it to be a bit more intuitive and maybe get backed by something cluster friendly like `redis`.

Who is the primary maintainer? I would submit to help in that respect if necessary.

**Comment by panuhorsmalahti** [comment]
I share your concerns. I have merge access but not npm publish access, so I've been waiting for a new release without merging PRs. I believe @indexzero is the primary maintainer.

I propose adding 1-2 maintainers and giving npm publish rights to more maintainers.

**Comment by indexzero** [comment]
@panuhorsmalahti 100% agree. I've made you and @sreuter Admins of this project. You also now have `npm` access. Please make the next release `1.0.0` to avoid any backwards compatibility issues with folks using the `^` for versioning as it behaves differently with modules before `1.0.0`
